### PR TITLE
Upgrade to PyTorch 2.3 and Python 3.11

### PR DESCRIPTION
**Pull request by staskh**

### CODE REVIEW

**Comment by rmaphoh** [comment]
Hi Staskh, thanks for your efforts in upgrading the packages and dependencies for AutoMorph. I tested the pull request on Google Cloud Platform (CUDA11.8, GPU T4) and observed that some errors occurred in M2. Have you observed a similar error?

```
Tue Jul  2 17:00:07 UTC 2024
### Preprocess Start ###
### Image Quality Assessment ###
INFO: CUDA is available. Using CUDA...
INFO: Using device cuda:0
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
INFO: Creating dataset with 3 examples
/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Epoch 1/1:   0%|                                                                                                            | 0/3 [00:00<?, ?img/s]Segmentation fault
Gradable cases by EyePACS_QA is 2 
Ungradable cases by EyePACS_QA is 1 
### Segmentation Modules ###
Tue Jul  2 17:00:16 UTC 2024
INFO: CUDA is available. Using CUDA...
INFO: Using device cuda:0
INFO: Creating dataset with 2 examples
Validation round:   0%|                                                                                                   | 0/1 [00:00<?, ?batch/s]Fatal Python error: Segmentation fault

Thread 0x00007ff18a238700 (most recent call first):
  File "/opt/conda/envs/automorph/lib/python3.11/threading.py", line 327 in wait
  File "/opt/conda/envs/automorph/lib/python3.11/multiprocessing/queues.py", line 231 in _feed
  File "/opt/conda/envs/automorph/lib/python3.11/threading.py", line 982 in run
  File "/opt/conda/envs/automorph/lib/python3.11/threading.py", line 1045 in _bootstrap_inner
  File "/opt/conda/envs/automorph/lib/python3.11/threading.py", line 1002 in _bootstrap

Thread 0x00007ff163fff700 (most recent call first):
  File "/opt/conda/envs/automorph/lib/python3.11/threading.py", line 331 in wait
  File "/opt/conda/envs/automorph/lib/python3.11/threading.py", line 629 in wait
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/tqdm/_monitor.py", line 60 in run
  File "/opt/conda/envs/automorph/lib/python3.11/threading.py", line 1045 in _bootstrap_inner
  File "/opt/conda/envs/automorph/lib/python3.11/threading.py", line 1002 in _bootstrap

Current thread 0x00007ff272457740 (most recent call first):
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 456 in _conv_forward
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 460 in forward
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541 in _call_impl
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532 in _wrapped_call_impl
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217 in forward
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541 in _call_impl
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532 in _wrapped_call_impl
  File "/home/jupyter/automorph_test/AutoMorph/M2_Vessel_seg/model.py", line 108 in forward
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541 in _call_impl
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532 in _wrapped_call_impl
  File "/home/jupyter/automorph_test/AutoMorph/M2_Vessel_seg/model.py", line 42 in forward
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541 in _call_impl
  File "/opt/conda/envs/automorph/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532 in _wrapped_call_impl
  File "/home/jupyter/automorph_test/AutoMorph/M2_Vessel_seg/test_outside_integrated.py", line 114 in segment_fundus
  File "/home/jupyter/automorph_test/AutoMorph/M2_Vessel_seg/test_outside_integrated.py", line 239 in test_net
  File "/home/jupyter/automorph_test/AutoMorph/M2_Vessel_seg/test_outside_integrated.py", line 307 in <module>

Extension modules: numpy._core._multiarray_umath, numpy._core._multiarray_tests, numpy.linalg._umath_linalg, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.ops, pandas._libs.hashing, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, PIL._imaging, PIL._imagingft, scipy._lib._ccallback_c, scipy.ndimage._nd_image, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.special._ellip_harm_2, _ni_label, scipy.ndimage._ni_label, skimage._shared.geometry, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, kiwisolver._cext, skimage.morphology._misc_cy, skimage.measure._ccomp, _skeletonize_3d_cy, skimage.morphology._skeletonize_3d_cy, skimage.morphology._skeletonize_cy, skimage.measure._pnpoly, skimage.morphology._convex_hull, skimage.morphology._grayreconstruct, skimage.morphology._extrema_cy, skimage.morphology._flood_fill_cy, skimage.morphology._max_tree (total: 116)
Segmentation fault
```

**Comment by staskh** [comment]
Thank you for your note - I tested on Mac M2 - both with MPS and CPU configurations, - worked well. I'll test with CUDA shortly and let you know...
Just in case - here is my "conda list":
```
% conda list
# packages in environment at /Users/staskh/miniconda3/envs/automorph:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h80987f9_6  
ca-certificates           2024.3.11            hca03da5_0  
contourpy                 1.2.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
efficientnet-pytorch      0.7.1                    pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
fonttools                 4.53.0                   pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
imageio                   2.34.2                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
libffi                    3.4.4                hca03da5_1  
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.0                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h313beb8_0  
networkx                  3.3                      pypi_0    pypi
numpy                     2.0.0                    pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
openssl                   3.0.14               h80987f9_0  
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.0            py311hca03da5_0  
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.11.9               hb885b13_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
readline                  8.2                  h1a28f6b_0  
scikit-image              0.24.0                   pypi_0    pypi
scipy                     1.14.0                   pypi_0    pypi
setuptools                69.5.1          py311hca03da5_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.45.3               h80987f9_0  
sympy                     1.12.1                   pypi_0    pypi
tifffile                  2024.6.18                pypi_0    pypi
tk                        8.6.14               h6ba3021_0  
torch                     2.3.1                    pypi_0    pypi
torchvision               0.18.1                   pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
wheel                     0.43.0          py311hca03da5_0  
xz                        5.4.6                h80987f9_1  
zlib                      1.2.13               h18a0788_1
```

**Comment by staskh** [comment]
I updated the installation instructions and tested on CUDA 12.1 machine - everything works ok - see configuration details below.

I also intentionally tested mismatched configuration - NVIDIA driver 11.7, but installed PyTorch 2.3.1+cu121 and got an error similar to yours. Please check your configuration:
```
# check NVIDIA drivers
nvcc --version 
# check pytorch installation
python -c "import torch; print(torch.__version__);print(torch.version.cuda);print(torch.randn(1).cuda())"
```
In the case of a CUDA version mismatch, you can see very weird problems.

----------
Configuration I tested:
Host: AWS g4dn.2xlarge (Tesla T4 GPU)
AMI: ami-026ddff86be63eb51 Deep Learning OSS Nvidia Driver AMI GPU PyTorch 2.3.0 (Amazon Linux 2) 20240625
https://aws.amazon.com/releasenotes/aws-deep-learning-ami-gpu-pytorch-2-3-amazon-linux-2/ 

Followed LOCAL.md instructions ad then run ```source run.sh```

just in case, here is conda list:
```
# packages in environment at /opt/conda/envs/automorph:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0            16_linux64_mkl    conda-forge
brotli-python             1.1.0           py311hb755f60_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.6.2             hbcca054_0    conda-forge
certifi                   2024.6.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py311hb3a22ac_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1                    pypi_0    pypi
cuda-cudart               12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.5.39                       0    nvidia
cuda-runtime              12.1.0                        0    nvidia
cuda-version              12.5                          3    nvidia
cycler                    0.12.1                   pypi_0    pypi
efficientnet-pytorch      0.7.1                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.15.4             pyhd8ed1ab_0    conda-forge
fonttools                 4.53.0                   pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
fsspec                    2024.6.1                 pypi_0    pypi
gettext                   0.22.5               h59595ed_2    conda-forge
gettext-tools             0.22.5               h59595ed_2    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gmpy2                     2.1.5           py311hc4f1f91_1    conda-forge
gnutls                    3.6.15               he1e5248_0    https://aws-ml-conda.s3.us-west-2.amazonaws.com
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.11.0                   pypi_0    pypi
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
imageio                   2.34.2                   pypi_0    pypi
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    conda-forge
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.15                 hfd0df8a_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libasprintf               0.22.5               h661eb56_2    conda-forge
libasprintf-devel         0.22.5               h661eb56_2    conda-forge
libblas                   3.9.0            16_linux64_mkl    conda-forge
libcblas                  3.9.0            16_linux64_mkl    conda-forge
libcublas                 12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufile                 1.10.0.4                      0    nvidia
libcurand                 10.3.6.39                     0    nvidia
libcusolver               11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libdeflate                1.17                 h0b41bf4_0    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgettextpo              0.22.5               h59595ed_2    conda-forge
libgettextpo-devel        0.22.5               h59595ed_2    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libidn2                   2.3.7                hd590300_0    conda-forge
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
liblapack                 3.9.0            16_linux64_mkl    conda-forge
liblapacke                3.9.0            16_linux64_mkl    conda-forge
libnpp                    12.0.2.50                     0    nvidia
libnsl                    2.0.1                hd590300_0    conda-forge
libnvjitlink              12.1.105                      0    nvidia
libnvjpeg                 12.1.1.14                     0    nvidia
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libtasn1                  4.19.0               h166bdaf_0    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
llvm-openmp               15.0.7               h0cdce71_0    https://aws-ml-conda.s3.us-west-2.amazonaws.com
markupsafe                2.1.5           py311h459d7ec_0    conda-forge
matplotlib                3.9.0                    pypi_0    pypi
mkl                       2022.1.0           h84fe81f_915    https://aws-ml-conda.s3.us-west-2.amazonaws.com
mkl-devel                 2022.1.0           ha770c72_916    conda-forge
mkl-include               2022.1.0           h84fe81f_915    conda-forge
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.1                h9458935_1    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
nettle                    3.7.3                hbbd107a_1    https://aws-ml-conda.s3.us-west-2.amazonaws.com
networkx                  3.3                pyhd8ed1ab_1    conda-forge
numpy                     1.26.4                   pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openh264                  2.1.1                h780b84a_0    https://aws-ml-conda.s3.us-west-2.amazonaws.com
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.3.1                h4ab18f5_1    conda-forge
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.0                    pypi_0    pypi
pillow                    10.3.0                   pypi_0    pypi
pip                       24.0               pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.9          hb806964_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.11                    4_cp311    conda-forge
pytorch                   2.3.1           py3.11_cuda12.1_cudnn8.9.2_0    pytorch
pytorch-cuda              12.1                 ha16c6d3_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1           py311h459d7ec_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
scikit-image              0.24.0                   pypi_0    pypi
scipy                     1.14.0                   pypi_0    pypi
setuptools                70.1.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sympy                     1.12.1          pypyh2585a3b_103    conda-forge
tbb                       2021.8.0             hdb19cb5_0    https://aws-ml-conda.s3.us-west-2.amazonaws.com
tifffile                  2024.7.2                 pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
torchaudio                2.3.1               py311_cu121    pytorch
torchtriton               2.3.1                     py311    pytorch
torchvision               0.18.1              py311_cu121    pytorch
tqdm                      4.66.4                   pypi_0    pypi
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstandard                 0.22.0          py311hb6f056b_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

**Comment by rmaphoh** [comment]
Thanks. Successfully tested on Google Cloud Platform GPU (CUDA 11.8, PyTorch 2.3.1+cu11.8), CPU, and Macbook Air M2.

**Pull request merged**
